export const fall2023 = [
	{
		name: "Andrew Bertaina",
		slug: "bertaina",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/whales.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Patricia Q. Bidar",
		slug: "bidar",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/doors.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Avitus B. Carle",
		slug: "carle",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/airplane.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Kathy Fish",
		slug: "fish",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/cone.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Eliot Li",
		slug: "li",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/apron.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Jennifer Martelli",
		slug: "martelli",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/jung.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Douglas A. Martin",
		slug: "martin",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/fawn.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Cheryl Pappas",
		slug: "pappas",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/reddress.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "M.A. Scott",
		slug: "scott",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/petticoat.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "Eileen Tomarchio",
		slug: "tomarchio",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/octopus.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: false,
		slug: false,
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/lambette.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
	{
		name: "pod-ette",
		slug: "podette",
		link: "podette",
		imageSrc: import.meta.env.BASE_URL + "images/fall2023/podette.webp",
		instagram: "https://instagram.com",
		facebook: "https://facebook.com",
		twitter: "https://twitter.com/",
	},
];
