export const winter2024 = [
	{
		name: "Kelli Russell Agodon",
		slug: "agodon",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/agodon_small.jpg",
		instagram: "share",
		twitter: "share",
		bluesky: "share"
	},
	{
		name: "Amy Barnes",
		slug: "barnes",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/barnes_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Genia Blum",
		slug: "blum",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/blum_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Michael Czyzniejewski",
		slug: "czyzniejewski",
		imageSrc:
			import.meta.env.BASE_URL + "images/winter2024/czyniejwski_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Jeffrey Hecker",
		slug: "hecker",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/hecker_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Jenn Hollmeyer",
		slug: "hollmeyer",
		imageSrc:
			import.meta.env.BASE_URL + "images/winter2024/hollmeyer_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Marc Kaufman",
		slug: "kaufman",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/kaufman_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Douglas A. Martin",
		slug: "martin",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/martin_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Lynn Mundell",
		slug: "mundell",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/mundell_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Jessica Purdy",
		slug: "purdy",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/purdy_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Francine Witte",
		slug: "witte",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/witte_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
	{
		name: "Lucy Zhang",
		slug: "zhang",
		imageSrc: import.meta.env.BASE_URL + "images/winter2024/zhang_small.jpg",
		instagram: "share",
		bluesky: "share",
		twitter: "share",
	},
];
